FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /workspace
COPY pom.xml ./
COPY weiyou-common ./weiyou-common
COPY weiyou-modules ./weiyou-modules
COPY weiyou-boot ./weiyou-boot

RUN mvn -q -DskipTests -pl weiyou-boot/weiyou-app-server -am package

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=builder /workspace/weiyou-boot/weiyou-app-server/target/weiyou-app-server-0.1.0-SNAPSHOT.jar /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
